server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-user?useSSL=false
    username: root
    password: mysql@bjz0517
    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: userservice
#  cloud:
#    nacos:
#      server-addr: localhost:8848
#      discovery:
#        cluster-name: XA
#  rabbitmq:
#    host: 192.168.186.224
#    port: 5672
#    username: itcast
#    password: 123321
#    virtual-host: /         # 虚拟主机
#    listener:
#      simple:
#        prefetch: 1      # 预取机制：默认取无数个/一直取。1为取一个消费完之后再取
mybatis:
  type-aliases-package: com.bjz.user.commom.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.bjz: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
pattern:
  commonValue: 本地环境